US08 - Trainers Btn Return & Fix CSS
WildCodeSchool-2024-09/JS-RemoteFR-Crew404-P2-Pokeflex pull request #54
Opened 2024-11-26 15:37 UTC by ElodieMons

Ajout du Bouton retour sur la page Trainers
Fix CSS Trainers

2024-11-26 16:08 UTC, NzlThomas requested changes
Attention dans ton TrainerCards.tsx il y a un test qui passe pas, sinon ça me semble bon !

2024-11-27 08:13 UTC, NzlThomas approved these changes

2024-11-27 08:15 UTC, Joey-dev85 approved these changes

2024-11-27 08:23 UTC, GorskiAnthony approved these changes

2024-11-27 08:23 UTC, merged